
name = "DashMoreComponents"
uuid = "1b08a953-4be3-4667-9a23-dbcddf8f2e87"
authors = ["Ann Marie Ward <amward@fastmail.us>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
